name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/setup-node@v2
   
     - name: Setup NodeJs
       uses: actions/setup-node@v2
       with:
        node-version: 16.x
        
     - name: Install Dependecies
       run: npm install  
      
     - uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: "test"
  
